### ISSUE TITLE
Allow users to specify which block types enter should insert a paragraph

### ISSUE THREAD

**Issue by cameracker** [victorbueno/slate-auto-exit-block#2]
Some users may want to have headers insert additional headers depending on their use case, so hard coding types limits the usefulness of this plugin.

Change the plugin to accept an options object that allows the caller to specify the block types where enter should result in the insertion of the default block type.

**Comment by cameracker** [comment]
This also goes for `li`, not all users have `li` as a type, some users have `numbered-list-item` or `ordered-list-item` etc, so if there's special exit behavior for that type, it should be captured in the options object.

**Comment by victorbueno** [comment]
@CameronAckermanSEL Hey. Thank you for the request. I just changed the plugin to cover the behavior you were asking. 

```javascript
AutoExitBlock({
    blockType: /^(h{1,6})$/,
    exitBlockType: 'paragraph'
  }),
  AutoExitBlock({
    blockType: 'blockquote',
    exitBlockType: 'paragraph',
    onEmptyBlock: true
  }),
  AutoExitBlock({
    blockType: 'li',
    exitBlockType: 'paragraph',
    onEmptyBlock: true,
    unwrap: true
  })
```

**Comment by cameracker** [comment]
looks good!
